services:
  mysql:
    container_name: container-mysql
    image: dataryzer/dataryzer_mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 41465490Fe
      MYSQL_DATABASE: dataryzer
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 5s
  node:
    container_name: container-node
    image: dataryzer/dataryzer_node:latest
    environment:
      DB_PASSWORD: 41465490Fe
    ports:
      - "80:8080"
  angular:
    container_name: container-angular
    image: dataryzer/dataryzer_site_angular
    ports:
      - "4200:4200"
  java:
    container_name: container-java
    image: fabiosptech/java-dataryzer:v1
    depends_on:
      mysql:
        condition: service_healthy


