FROM openjdk:21-jdk-slim

RUN apt-get update && apt-get install -y maven git

RUN git clone https://github.com/PI-grupo05/Java.git

RUN mvn install -f Java/pom.xml

CMD ["java", "-jar", "Java/target/leitura-arquivos-excel-1.0-SNAPSHOT-jar-with-dependencies.jar"]
